site_name: apklis-downloader
site_description: Cliente Python para Apklis.cu con soporte de descarga asíncrona y barra de progreso.
site_author: ElJoker
repo_name: ElJoker63/apklis-downloader
repo_url: https://github.com/ElJoker63/apklis-downloader

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    # Modo Claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Cambiar al modo oscuro
    # Modo Oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Cambiar al modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css

copyright: 'Desarrollado con ❤️ por ElJoker63. <code><\/\>+☕️=z17</code>'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ElJoker63/apklis-downloader

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html

nav:
  - Inicio: index.md
  - Empezando:
    - Instalación: getting-started/installation.md
    - Primeros Pasos: getting-started/quickstart.md
  - Referencia de la API:
    - Cliente de API: api-reference/api.md
    - Descargador: api-reference/downloader.md
    - Utilidades: api-reference/utils.md
